---
- name: "Debian - Iniciando o Zabbix Agent"
  set_fact: zabbix_agent_service_name=zabbix-agent


- name: "Debian - Criando o script de inicializacao"
  template: src={{dir_dest}}/{{dir_zabbix}}/misc/init.d/debian/zabbix-agent dest=/etc/init.d/zabbix-agent owner=root group=root mode=0755

- name: "Debian - Ajustando o script de inicializacao zabbix-agent"
  blockinfile: 
   dest: /etc/init.d/zabbix-agent
   insertbefore: "NAME=zabbix_agentd"
   content: |
    ### BEGIN INIT INFO
    # Provides:          zabbix-agent
    # Required-Start:    $local_fs $remote_fs
    # Required-Stop:
    # X-Start-Before:    rmnologin
    # Default-Start:     2 3 4 5
    # Default-Stop:
    # Short-Description: Provide limited super user privileges to specific users
    # Description: Provide limited super user privileges to specific users. 
    ### END INIT INFO

- name: "Debian - Iniciando o zabbix-agent"
  service:
   name: "{{zabbix_agent_service_name}}"
   state: running
   enabled: yes
  notify: restart zabbix agent


