---
- name: "Ajustando o zabbix_agentd.conf"
  lineinfile:
   dest: /usr/local/etc/zabbix_agentd.conf
   regexp: "{{ item.regexp }}"
   line: "{{ item.line }}"
  with_items:
  - { regexp: '# LogFileSize=1' , line: 'LogFileSize=1024' }
  - { regexp: '# DebugLevel=3'  , line: 'DebugLevel=3' }
  - { regexp: 'Server=127.0.0.1', line: 'Server={{zabbix_server}}' }
  - { regexp: 'ServerActive=127.0.0.1' , line: 'ServerActive={{zabbix_server}}' }
  - { regexp: 'Hostname=Zabbix server' , line: 'Hostname={{ansible_hostname}}' }
  tags: conf
